apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomcontroller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/eks/app
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sourcecontroller
  targetNamespace: prueba
  timeout: 3m0s
  wait: true
