apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomcontroller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/eks
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sourcecontroller
  targetNamespace: prueba
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
        spec:
          minReplicas: 3             
      target:
        name: app
        kind: HorizontalPodAutoscaler
